spring:
  application:
    name: backend

  datasource:
    url: ${mysql.database.url:jdbc:mysql://localhost:3306/ApparelAvenue}
    username: ${mysql.database.username:root}
    password: ${mysql.database.password:root}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1200

upload:
  file:
    banner: "banner-image"